---
title: "SOCS0100_Assignment1"
format: html
editor: visual
---

## Part I-A Data Exploration and Contextualisation

The chosen dataset for this assignment was released by the WHO, which displays the immunisation coverage among 1 year olds between 1974 and 2015 for diseases such as Tuberculosis (the data doesn't explicitly say tuberculosis immunisation coverage, because the disease is protected by the BCG vaccine), Hepatitis B, Diphtheria, Tetanus, Polio, and Measles in different regions of the world. It also includes data of the number of confirmed cases for Tetanus, Polio, Pertussis, Measles, and Diphtheria. Finally, the dataset showcases the estimated deaths due to tuberculosis excluding HIV.

We will begin by defining one of the key variables in the dataset - immunisation coverage. It is the outcome of successful vaccination which accounts for full immunity to the disease. This dataset was chosen for this assessment as it is highly relevant in today’s social science studies. It wishes to determine the relationship between immunisation coverage and the resulting number of confirmed cases. This could be a potential indicator of the minimum immunisation coverage that is needed to reduce cases.

After further inspection of the dataset, we notice that all diseases are part of the “Routine Immunisation Schedule”, which is a recommended vaccination schedule [\[1\]](#_msocom_1) by a country’s health department to be completed before the age of 1.

The dataset is thus useful when judging the overall quality of the country’s health care system, and whether it is consistent. Because some of these diseases require more than just one dose. Let us look at the DTP3 vaccine, the third dose for prevention of Diphtheria and Tetanus as an example. A low immunisation coverage and of Diphtheria and Tetanus may thus be a potential suggestion of a low consistency in the country’s healthcare system because people *need* to have 3 doses to have full immunity. There is thus high relevance of this dataset in social science, as it allows exploration of how social phenomenon influences the general state of a country’s healthcare [\[2\]](#_msocom_1) system.

Finally, in terms of missing values (NA), the dataset contains quite a significant missing values. There is no clear pattern in these but in general, many missing values are from countries with less developed healthcare systems, and are during the years before the 2000s. These descriptive findings are not unexpected as it is likely that these countries didn't have the means to record data given their social and economic situations.

[\[2\]](#_msoanchor_1)<https://www.kcl.ac.uk/kghi/research/health-and-social-science>

[\[1\]](#_msoanchor_1)<https://www.sciencedirect.com/topics/immunology-and-microbiology/vaccination-schedule#:~:text=A%20vaccination%20schedule%20is%20defined,is%20effectively%20built%20and%20sustained>.

## Part I-B Data Processing and Functional Programming

This section aims to carry out 3 data wrangling using libraries such as Tidyverse packages, like dyplr. The first operation is renaming the dataset columns after having carried out all the necessary steps before hand (Removing everything in my environment and setting up working directory, downloading required packages such as pacman, and importing the "vaccine_2017.csv" data.)

The table below shows the first 5 rows of the raw vaccine data.

```{r}
#| label: fig-First-5-rows-of-raw-vaccine-data.
#| fig-cap: First-5-rows-of-raw-vaccine-data.
#| message: false
#| echo: false
if (!require("pacman")) {
  install.packages("pacman")
}

pacman::p_load(
  tidyverse, 
  kableExtra,
  flextable, 
  skimr) 

data <- read.csv("vaccine_2017.csv", header = TRUE)

knitr::kable(head(data, 5))
```

As shown in Figure 1, the column labels are extremely long and complicated.
